=== marzack87/app-serv-web/public_webapp/web/xml-types/XML_Schema.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="username"/>
                            <xs:element type="xs:string" name="password"/>
                            <xs:element type="xs:string" name="name"/>
                            <xs:element type="xs:string" name="surname"/>
                            <xs:element type="xs:string" name="phone"/>
                            <xs:element type="xs:string" name="admin" default="0"/>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="user_name" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="apartments">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="apartment" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="id"/>
                            <xs:element type="xs:string" name="indirizzo"/>
                            <xs:element type="xs:string" name="civico"/>
                            <xs:element type="xs:string" name="citta"/>
                            <xs:element type="xs:string" name="tipo_alloggio"/>
                            <xs:element type="xs:string" name="tipo_cucina"/>
                            <xs:element type="xs:string" name="bagni"/>
                            <xs:element type="xs:string" name="camere_letto"/>
                            <xs:element type="xs:string" name="n_piano"/>
                            <xs:element type="xs:string" name="ascensore"/>
                            <xs:element type="xs:string" name="garage"/>
                            <xs:element type="xs:string" name="terrazzo"/>
                            <xs:element type="xs:string" name="posti_totali"/>
                            <xs:element type="xs:string" name="posti_liberi"/>
                            <xs:element type="xs:string" name="prezzo_posto"/>
                            <xs:element type="xs:string" name="spese_acqua"/>
                            <xs:element type="xs:string" name="spese_gas"/>
                            <xs:element type="xs:string" name="spese_luce"/>
                            <xs:element type="xs:string" name="spese_condominiali"/>
                            <xs:element type="xs:string" name="nessune_spese"/>
                            <xs:element name="images" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="image" maxOccurs="unbounded" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="user_name" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="search">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="indirizzo"/>
                <xs:element type="xs:string" name="prezzo"/>
                <xs:element type="xs:string" name="posti_liberi"/>
                <xs:element type="xs:string" name="tipologia"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="search_result">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="result" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="img"/>
                            <xs:element type="xs:string" name="description"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== marzack87/app-serv-web/public_webapp/web/WEB-INF/xml/users.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../../xml-types/XML_Schema.xsd">
<user user_name="admin">
<username>admin</username>
<password>admin</password>
<name>Amministratore</name>
<surname>Del Mondo</surname>
<phone>7777777</phone>
<admin>1</admin>
</user>
<user user_name="walt">
<username>walt</username>
<password>heisenberg</password>
<name>Walter</name>
<surname>White</surname>
<phone>(505) 555-1258</phone>
<admin>0</admin>
</user>
<user user_name="homer">
<username>homer</username>
<password>password</password>
<name>Homer</name>
<surname>Simpson</surname>
<phone>(939) 555-0113</phone>
<admin>0</admin>
</user>
<user user_name="shelly">
<username>shelly</username>
<password>bazinga</password>
<name>Sheldon</name>
<surname>Cooper</surname>
<phone>(294) 555-9264</phone>
<admin>0</admin>
</user>
<user user_name="monopoli">
<username>monopoli</username>
<password>monopoli</password>
<name>Signor</name>
<surname>Monopoli</surname>
<phone>(+39) 01-1738634</phone>
<admin>0</admin>
</user>
</users>
